// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiJjH_mjJtm_WZNV0-V6Ua8YNbpxRx6zg',
    appId: '1:330151280349:web:278090e916a01e3de9a534',
    messagingSenderId: '330151280349',
    projectId: 'signin-7ab20',
    authDomain: 'signin-7ab20.firebaseapp.com',
    storageBucket: 'signin-7ab20.appspot.com',
    measurementId: 'G-2N2TECTZE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv-uVDpGu39UZSITtJHbd6FCGGf9c7NL8',
    appId: '1:330151280349:android:09897f9cd4ed8a66e9a534',
    messagingSenderId: '330151280349',
    projectId: 'signin-7ab20',
    storageBucket: 'signin-7ab20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfw0V7d18hV5kuQyBtvRFE1PmflMZ3pmA',
    appId: '1:330151280349:ios:d8cf8754e211e857e9a534',
    messagingSenderId: '330151280349',
    projectId: 'signin-7ab20',
    storageBucket: 'signin-7ab20.appspot.com',
    iosBundleId: 'com.example.calculatorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfw0V7d18hV5kuQyBtvRFE1PmflMZ3pmA',
    appId: '1:330151280349:ios:171b89df60ed9e91e9a534',
    messagingSenderId: '330151280349',
    projectId: 'signin-7ab20',
    storageBucket: 'signin-7ab20.appspot.com',
    iosBundleId: 'com.example.calculatorapp.RunnerTests',
  );
}
